[workspace]
# members = ["aoc", "aoc-client", "cargo-aoc-setup", "parsers", "challenges/*"]
members = ["challenges/day11"]
resolver = "2"

# [profile.dev.package.'*']
# opt-level = 3

# [profile.release]
# debug = true
